name: RobotFmk CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Run tests
      run: |
        # Instalar dependencias de testing
        pip install -r requirements.txt
        # Ejecutar tests
        make test_actions
        #robot -r ./reports --variable BROWSER:chrome --variable BROWSER_OPTIONS:"--headless" tests/
        # robot -r ./reports -v BROWSER:chrome -v CHROME_OPTIONS:"{'args': ['--headless', '--disable-gpu', '--window-size=1920,1080', '--user-data-dir=/tmp/chrome-user-data']}" tests/avis_navigation.robot
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: report
        path: tests/
        if-no-files-found: 'warn'
        retention-days: 30