name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
        image: selenium/standalone-chrome

    steps:
    - name: Checkout code
      run: |
        chmod -R 777 /__w/_temp
        actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        robot -r ./reports tests/avis_navigation.robot
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: reports/
        if-no-files-found: 'warn'
        retention-days: 10
