name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Chrome
      run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        export CHROME_BIN=/usr/bin/chromium-browser
        robot -r ./reports tests/avis_navigation.robot
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: reports/
        if-no-files-found: 'warn'
        retention-days: 10
