name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome
    steps:
      - name: Install git
        run: |
          sudo apt-get update
          sudo apt-get install -y git
      - name: Checkout code
        run: |
          git clone --depth 1 https://github.com/javice/RobotFwk_E2E_Test
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          robot -r ./reports tests/avis_navigation.robot
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/
          if-no-files-found: 'warn'
          retention-days: 10
